import fs from 'node:fs';
import path from 'node:path';
import { isAutoGeneratedArticle } from '../../scripts/lib/provenance.mjs';
import { getCategory, NEWS_AND_TRENDS } from './articleTypes';
import { getSeoTitle } from './seo';

export interface ArticleSummary {
  slug: string;
  title: string;
  date: string;
  type: string;
  description: string;
  tags: string[];
  readingTime: number;
  searchContent?: string;
}

// Only standalone Paper Reviews are noindexed (src/app/writing/[slug]/page.tsx);
// every other type renders as an indexable page. Shared so listing and
// recommendation code can steer internal links toward pages that can rank.
export function isIndexableArticle(article: { type: string }): boolean {
  return article.type !== 'Paper Review';
}

// Canonical topics shown on the site. Every raw tag is mapped to one of
// these via TAG_ALIASES below. Tags without an alias entry are dropped
// from display (keeping the topic list tight).
const CANONICAL_TOPICS = [
  'LLM Security',
  'RAG Security',
  'Agent Security',
  'Data Poisoning',
  'AI Safety',
  'Privacy',
  'Adversarial ML',
  'Binary Analysis',
  'Code Security',
  'Watermarking',
  'Deepfakes & Biometrics',
  'Infrastructure Security',
  'Tools & Visualization',
] as const;

const TAG_ALIASES: Record<string, string> = {
  // LLM Security
  'LLM Security': 'LLM Security',
  'LLM': 'LLM Security',
  'Jailbreaking': 'LLM Security',
  'Prompt Injection': 'LLM Security',
  'Red Teaming': 'LLM Security',
  'LLM Red Teaming': 'LLM Security',
  'Model Abuse': 'LLM Security',
  'Safety Alignment': 'LLM Security',
  'Multimodal Large Language Models': 'LLM Security',
  'Mixture-of-Experts': 'LLM Security',
  // RAG
  'RAG': 'RAG Security',
  'RAG Security': 'RAG Security',
  'RAGDefender': 'RAG Security',
  // Agents
  'Agent Security': 'Agent Security',
  'Agentic AI': 'Agent Security',
  'Agentic Security': 'Agent Security',
  'Agentic Risk': 'Agent Security',
  'Agentic Misalignment': 'Agent Security',
  'Agent-Centric Security': 'Agent Security',
  'Agent Identity Protocol': 'Agent Security',
  'AI Agents': 'Agent Security',
  'LLM Agents': 'Agent Security',
  'Autonomous Agents': 'Agent Security',
  'Autonomous AI': 'Agent Security',
  'Autonomous Systems': 'Agent Security',
  'Multi-Agent Systems': 'Agent Security',
  'MCP': 'Agent Security',
  'A2A': 'Agent Security',
  'Protocol Security': 'Agent Security',
  'Tool-Calling': 'Agent Security',
  // Data Poisoning
  'Data Poisoning': 'Data Poisoning',
  'Backdoor Attacks': 'Data Poisoning',
  'Model Poisoning': 'Data Poisoning',
  'Supply-Chain Attack': 'Data Poisoning',
  'Software Supply Chain': 'Data Poisoning',
  'Geopolitical Supply Chain': 'Data Poisoning',
  // AI Safety
  'AI Safety': 'AI Safety',
  'Safety Policy': 'AI Safety',
  'Safety Certification': 'AI Safety',
  'AI Alignment': 'AI Safety',
  'Inference-Time Safety': 'AI Safety',
  'Reasoning Safety': 'AI Safety',
  'Mechanistic Interpretability': 'AI Safety',
  'Defense Trilemma': 'AI Safety',
  'Dual-Use Oversight': 'AI Safety',
  'Machine Unlearning': 'AI Safety',
  'Reinforcement Learning from Human Feedback': 'AI Safety',
  'Trust and Governance': 'AI Safety',
  'Governance': 'AI Safety',
  'Compositional Security': 'AI Safety',
  'Formal Defensive Architectures': 'AI Safety',
  'Cognitive State Planes': 'AI Safety',
  'Defense': 'AI Safety',
  'Defensive AI': 'AI Safety',
  // Privacy
  'Privacy': 'Privacy',
  'Data Privacy': 'Privacy',
  'Membership Inference': 'Privacy',
  'Differential Privacy': 'Privacy',
  // Adversarial ML
  'Adversarial Attacks': 'Adversarial ML',
  'Adversarial Testing': 'Adversarial ML',
  'Adversarial ML': 'Adversarial ML',
  'Contextual Attacks': 'Adversarial ML',
  'Injection Attacks': 'Adversarial ML',
  // Binary Analysis
  'Binary Analysis': 'Binary Analysis',
  'Reverse Engineering': 'Binary Analysis',
  'Neural Decompilation': 'Binary Analysis',
  'Code Similarity': 'Binary Analysis',
  'Program Analysis': 'Binary Analysis',
  // Code Security
  'Code Security': 'Code Security',
  'Vulnerabilities': 'Code Security',
  'Vulnerability Detection': 'Code Security',
  'Exploits': 'Code Security',
  'Fuzzing': 'Code Security',
  'RCE': 'Code Security',
  'Python Security': 'Code Security',
  'Deserialization': 'Code Security',
  'Automated Vulnerability Discovery': 'Code Security',
  'Bug Bounty Programs': 'Code Security',
  'Security Tools': 'Code Security',
  'EnsembleSHAP': 'Code Security',
  'SABLE': 'Code Security',
  // Watermarking
  'Watermarking': 'Watermarking',
  'AI-Generated Text': 'Watermarking',
  'Text Detection': 'Watermarking',
  'Text Classification': 'Watermarking',
  // Deepfakes & Biometrics
  'Deepfake': 'Deepfakes & Biometrics',
  'Biometrics': 'Deepfakes & Biometrics',
  // Infrastructure Security
  'Authentication Security': 'Infrastructure Security',
  'Credential Exposure': 'Infrastructure Security',
  'Authorization Boundaries': 'Infrastructure Security',
  'Privilege Escalation': 'Infrastructure Security',
  'System Compromise': 'Infrastructure Security',
  'System-Level Vulnerabilities': 'Infrastructure Security',
  'Intrusion Detection': 'Infrastructure Security',
  'Attack Detection': 'Infrastructure Security',
  'Evasion Techniques': 'Infrastructure Security',
  'Hardware Security': 'Infrastructure Security',
  'Nvidia Security': 'Infrastructure Security',
  'Prisma SASE': 'Infrastructure Security',
  'Advanced Persistent Threats': 'Infrastructure Security',
  'Cybercrime': 'Infrastructure Security',
  'Kinetic Risk': 'Infrastructure Security',
  'Operational Risks': 'Infrastructure Security',
  // Tools & Visualization
  'Data Visualization': 'Tools & Visualization',
  'Visualization': 'Tools & Visualization',
  'Best Practices': 'Tools & Visualization',
  'Dezoomify': 'Tools & Visualization',
  'Web Tooling': 'Tools & Visualization',
  'UX Design': 'Tools & Visualization',
  'Open Source': 'Tools & Visualization',
  'Vercel': 'Tools & Visualization',
  'Dart': 'Tools & Visualization',
  'Swift': 'Tools & Visualization',
  // AI Security catch-all
  'AI Security': 'LLM Security',
  'ML Security': 'LLM Security',
  'Deep Learning': 'LLM Security',
  'Neural Networks': 'LLM Security',
  'Generative AI': 'LLM Security',
  'NLP': 'LLM Security',
  'Survey': 'LLM Security',
  'Drug Detection': 'LLM Security',
  'Korean Language': 'LLM Security',
};

export function normalizeTags(rawTags: string[]): string[] {
  const canonical = new Set<string>();
  for (const tag of rawTags) {
    const mapped = TAG_ALIASES[tag];
    if (mapped) {
      canonical.add(mapped);
    }
  }
  // Preserve a stable order matching CANONICAL_TOPICS
  return CANONICAL_TOPICS.filter((t) => canonical.has(t));
}

export interface TagEntry {
  name: string;
  slug: string;
  count: number;
}

export interface TagLandingContent {
  lead: string;
  body: string;
  // Per-kind counts and the publication span, derived from the hub's articles.
  coverage: string;
  learnings: string[];
  relatedTags: string[];
  // Unique per hub (counts + newest title); the page truncates it for <meta>.
  metaDescription: string;
}

const articlesIndexPath = path.join(process.cwd(), 'src', 'data', 'articles-index.json');

export function getAllArticles(): ArticleSummary[] {
  const fileContents = fs.readFileSync(articlesIndexPath, 'utf8');
  const articles = JSON.parse(fileContents) as ArticleSummary[];
  return articles
    .map((a) => ({ ...a, tags: normalizeTags(a.tags || []) }))
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

// Hand-written pieces only (walkthroughs, research writeups, tutorials,
// projects) — everything the daily automation did NOT produce. Used by the
// homepage and the Writing page to keep Denis's own voice above the
// digest flood.
export function getRecentHandwrittenArticles(limit = 3): ArticleSummary[] {
  return getAllArticles()
    .filter((a) => !isAutoGeneratedArticle({ type: a.type, title: a.title, date: a.date }))
    .slice(0, limit);
}

export function slugifyTag(tag: string): string {
  return tag
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

export function getTagEntries(articles: ArticleSummary[] = getAllArticles()): TagEntry[] {
  const counts = new Map<string, number>();
  for (const article of articles) {
    for (const tag of article.tags) {
      counts.set(tag, (counts.get(tag) || 0) + 1);
    }
  }

  const usedSlugs = new Set<string>();
  const tags = Array.from(counts.keys()).sort((a, b) => a.localeCompare(b));

  return tags.map((tag) => {
    const base = slugifyTag(tag) || 'tag';
    let slug = base;
    let suffix = 2;
    while (usedSlugs.has(slug)) {
      slug = `${base}-${suffix}`;
      suffix += 1;
    }
    usedSlugs.add(slug);
    return { name: tag, slug, count: counts.get(tag) || 0 };
  });
}

export function getTagBySlug(tagSlug: string): string | null {
  const match = getTagEntries().find((entry) => entry.slug === tagSlug);
  return match?.name || null;
}

export function getTagSlugByName(tagName: string): string {
  const match = getTagEntries().find((entry) => entry.name === tagName);
  return match?.slug || slugifyTag(tagName) || 'tag';
}

export function getArticlesByTag(tagName: string): ArticleSummary[] {
  return getAllArticles().filter((article) => article.tags.includes(tagName));
}

// The /news/ hub and its feed are projections over the same corpus: articles
// keep their /writing/<slug>/ URLs; this only selects the News & Trends
// display category (daily digests + weekly trend reports).
export function getNewsArticles(): ArticleSummary[] {
  return getAllArticles().filter((article) => getCategory(article.type) === NEWS_AND_TRENDS);
}

export interface MonthGroup {
  key: string; // 'YYYY-MM'
  label: string; // 'July 2026'
  articles: ArticleSummary[];
}

// Bucket a newest-first article list into contiguous month groups for dense
// chronological listings (the /news/ hub). Input order is preserved.
export function groupArticlesByMonth(articles: ArticleSummary[]): MonthGroup[] {
  const groups: MonthGroup[] = [];
  for (const article of articles) {
    const key = article.date.slice(0, 7);
    let group = groups[groups.length - 1];
    if (!group || group.key !== key) {
      const label = new Date(`${key}-01T00:00:00Z`).toLocaleDateString('en-US', {
        month: 'long',
        year: 'numeric',
        timeZone: 'UTC',
      });
      group = { key, label, articles: [] };
      groups.push(group);
    }
    group.articles.push(article);
  }
  return groups;
}

// Prev/next navigation is scoped to the current article's reader-facing
// category. Strict chronology across the whole corpus would sandwich
// hand-written pieces between daily digests, so instead each category forms
// its own chronological chain.
export function getAdjacentArticles(slug: string): { prev: ArticleSummary | null; next: ArticleSummary | null } {
  const articles = getAllArticles();
  const index = articles.findIndex((a) => a.slug === slug);
  if (index === -1) return { prev: null, next: null };

  const category = getCategory(articles[index].type);

  // Articles are sorted newest-first: prev (older) scans forward, next (newer)
  // scans backward, each stopping at the nearest article in the same category.
  let prev: ArticleSummary | null = null;
  for (let i = index + 1; i < articles.length; i++) {
    if (getCategory(articles[i].type) === category) {
      prev = articles[i];
      break;
    }
  }

  let next: ArticleSummary | null = null;
  for (let i = index - 1; i >= 0; i--) {
    if (getCategory(articles[i].type) === category) {
      next = articles[i];
      break;
    }
  }

  return { prev, next };
}

export interface NewsWeekCluster {
  // The weekly trend report that wraps up the window; null for a trend report
  // itself and for digests whose week has no report yet.
  weekly: ArticleSummary | null;
  // Daily digests inside the window, newest first, excluding the current one.
  dailies: ArticleSummary[];
}

const WEEK_WINDOW_DAYS = 6;
const DAY_MS = 86_400_000;

function dayNumber(date: string): number {
  return Math.floor(new Date(`${date}T00:00:00Z`).getTime() / DAY_MS);
}

// Same-week companions of a News & Trends article. A weekly report covers the
// seven days ending on its date; a daily digest belongs to the nearest weekly
// published within six days after it. Digests and weeklies otherwise only meet
// in the /news/ list and the prev/next chain, so this gives every issue a
// small, fully indexable cluster of in-links (daily <-> weekly, daily <->
// daily) rather than leaning on the hub alone.
export function getNewsWeekCluster(
  slug: string,
  articles: ArticleSummary[] = getAllArticles(),
): NewsWeekCluster {
  const current = articles.find((a) => a.slug === slug);
  if (!current || getCategory(current.type) !== NEWS_AND_TRENDS) {
    return { weekly: null, dailies: [] };
  }
  const news = articles.filter((a) => getCategory(a.type) === NEWS_AND_TRENDS);
  const day = dayNumber(current.date);

  let weekly: ArticleSummary | null = null;
  if (current.type !== 'Trend Report') {
    // Newest-first scan: distances shrink toward zero, so the last in-window
    // match before they turn negative is the nearest covering weekly.
    for (const candidate of news) {
      if (candidate.type !== 'Trend Report') continue;
      const distance = dayNumber(candidate.date) - day;
      if (distance < 0) break;
      if (distance <= WEEK_WINDOW_DAYS) weekly = candidate;
    }
  }

  const end = weekly ? dayNumber(weekly.date) : day;
  const start = end - WEEK_WINDOW_DAYS;
  const dailies = news.filter((a) => {
    if (a.type === 'Trend Report' || a.slug === slug) return false;
    const d = dayNumber(a.date);
    return d >= start && d <= end;
  });

  return { weekly, dailies };
}

// Newest issues for the compact "news desk" blocks on / and /writing/.
export function getLatestNewsDesk(dailyLimit = 3): { weekly: ArticleSummary | null; dailies: ArticleSummary[] } {
  const news = getNewsArticles();
  return {
    weekly: news.find((a) => a.type === 'Trend Report') ?? null,
    dailies: news.filter((a) => a.type === 'News Digest').slice(0, dailyLimit),
  };
}

export interface HubGroups {
  // Walkthroughs, research papers, tutorials, projects — Denis's own writing.
  handwritten: ArticleSummary[];
  // Daily digests and weekly trend reports.
  news: ArticleSummary[];
  // Standalone paper reviews (noindexed; listed compactly).
  reviews: ArticleSummary[];
}

// Split a hub's article list so the indexable, most distinctive content comes
// first and the noindexed review backlog does not dominate the page.
export function groupArticlesForHub(articles: ArticleSummary[]): HubGroups {
  const groups: HubGroups = { handwritten: [], news: [], reviews: [] };
  for (const article of articles) {
    if (article.type === 'Paper Review') groups.reviews.push(article);
    else if (getCategory(article.type) === NEWS_AND_TRENDS) groups.news.push(article);
    else groups.handwritten.push(article);
  }
  return groups;
}

// Related-article scoring. Pure tag overlap is a weak signal here — the
// canonical topics are broad enough that most of the corpus shares a tag —
// so ranking also rewards same-category affinity and recency. Weights keep
// tag overlap dominant: one extra shared tag (3) outweighs the category
// bonus (1.5) plus the maximum recency boost (1).
const RELATED_TAG_WEIGHT = 3;
const RELATED_CATEGORY_BONUS = 1.5;
// e-folding time of the recency boost: ~6 months old ≈ 0.37, ~1 year ≈ 0.13.
const RELATED_RECENCY_DECAY_DAYS = 180;

export function getRelatedArticles(
  currentSlug: string,
  currentTags: string[],
  limit = 3,
  articles: ArticleSummary[] = getAllArticles(),
): ArticleSummary[] {
  const currentTagSet = new Set(currentTags);
  const current = articles.find((a) => a.slug === currentSlug) ?? null;
  const currentCategory = current ? getCategory(current.type) : null;
  const currentIsHandwritten = current
    ? !isAutoGeneratedArticle({ type: current.type, title: current.title, date: current.date })
    : false;
  const currentIsIndexable = current ? isIndexableArticle(current) : true;
  const now = Date.now();

  return articles
    .filter((article) => {
      if (article.slug === currentSlug) return false;
      // Hand-written pieces never recommend the daily digest feed: with the
      // shared-tag corpus this dense, digests would otherwise crowd out
      // Denis's own related writing.
      if (currentIsHandwritten && getCategory(article.type) === NEWS_AND_TRENDS) return false;
      // Indexable pages never recommend noindexed paper reviews: each such
      // link spends an indexable page's equity on a URL that cannot rank, and
      // the day's digest already covers the review. Reviews may still
      // recommend each other.
      if (currentIsIndexable && !isIndexableArticle(article)) return false;
      return true;
    })
    .map((article) => {
      const sharedTagCount = article.tags.filter((tag) => currentTagSet.has(tag)).length;
      const categoryBonus =
        currentCategory !== null && getCategory(article.type) === currentCategory
          ? RELATED_CATEGORY_BONUS
          : 0;
      const ageDays = Math.max(0, (now - new Date(article.date).getTime()) / 86_400_000);
      const recencyBoost = Math.exp(-ageDays / RELATED_RECENCY_DECAY_DAYS);
      const score = sharedTagCount * RELATED_TAG_WEIGHT + categoryBonus + recencyBoost;
      return { article, sharedTagCount, score };
    })
    .filter((entry) => entry.sharedTagCount > 0)
    .sort((a, b) => {
      if (b.score !== a.score) {
        return b.score - a.score;
      }
      return new Date(b.article.date).getTime() - new Date(a.article.date).getTime();
    })
    .slice(0, limit)
    .map((entry) => entry.article);
}

const tagLandingOverrides: Record<string, { lead: string; body: string }> = {
  'RAG Security': {
    lead:
      'RAG security sits at the intersection of retrieval quality, prompt safety, and model reliability. A secure RAG pipeline is not just about better answers: it is about ensuring that retrieved context cannot quietly steer generation toward harmful, incorrect, or attacker-controlled behavior.',
    body:
      'The articles in this topic focus on practical failure modes such as corpus poisoning, retrieval manipulation, and privacy leakage. They also cover defenses that can be adopted in production systems without heavy overhead, including robust filtering, retrieval-time verification, and safer prompt orchestration.',
  },
  'LLM Security': {
    lead:
      'LLM security is a systems problem that spans model behavior, agent tooling, and data pipelines. Effective hardening requires understanding how attacks emerge across prompt inputs, external tools, retrieval connectors, and post-processing layers.',
    body:
      'This topic tracks jailbreak strategies, poisoning methods, alignment bypass techniques, and concrete mitigation patterns. The goal is to separate research hype from operational reality by summarizing what attacks actually transfer, what defenses degrade gracefully, and where high-risk blind spots remain.',
  },
  Privacy: {
    lead:
      'Privacy risks in modern AI systems are not limited to obvious data leaks. They also appear through indirect channels such as membership inference, memorization extraction, and retrieval traces that expose sensitive context.',
    body:
      'These articles analyze how privacy leakage happens in practice and what engineering controls reduce exposure. You will find discussions on threat modeling, evaluation methods, and lightweight safeguards that can be integrated into existing model and RAG deployments.',
  },
};

function pluralize(count: number, singular: string, plural = `${singular}s`): string {
  return `${count} ${count === 1 ? singular : plural}`;
}

function joinWithAnd(items: string[]): string {
  if (items.length <= 1) return items.join('');
  if (items.length === 2) return `${items[0]} and ${items[1]}`;
  return `${items.slice(0, -1).join(', ')}, and ${items[items.length - 1]}`;
}

function formatMonthYear(date: string): string {
  return new Date(`${date.slice(0, 7)}-01T00:00:00Z`).toLocaleDateString('en-US', {
    month: 'long',
    year: 'numeric',
    timeZone: 'UTC',
  });
}

const HANDWRITTEN_KIND_LABELS: Record<string, string> = {
  'Paper Walkthrough': 'paper walkthrough',
  'Research Paper': 'research paper',
  Tutorial: 'tutorial',
  Project: 'project',
};

// "7 paper walkthroughs, 2 research papers, and 1 tutorial", most common first.
function describeHandwrittenKinds(articles: ArticleSummary[]): string {
  const counts = new Map<string, number>();
  for (const article of articles) {
    const label = HANDWRITTEN_KIND_LABELS[article.type] ?? article.type.toLowerCase();
    counts.set(label, (counts.get(label) || 0) + 1);
  }
  return joinWithAnd(
    Array.from(counts.entries())
      .sort((a, b) => b[1] - a[1])
      .map(([label, count]) => pluralize(count, label)),
  );
}

// Landing copy for a tag hub. Apart from the three hand-written overrides,
// every sentence is derived from the hub's own articles (counts by kind,
// publication span, newest titles, co-occurring topics), so two hubs share
// only connective words. The previous fixed template made the intro of every
// non-override hub read identically, which is what "Crawled - currently not
// indexed" tends to punish on thin collection pages.
export function getTagLandingContent(tagName: string, articles: ArticleSummary[]): TagLandingContent {
  const relatedTagCounts = new Map<string, number>();
  for (const article of articles) {
    for (const tag of article.tags) {
      if (tag !== tagName) {
        relatedTagCounts.set(tag, (relatedTagCounts.get(tag) || 0) + 1);
      }
    }
  }
  const topRelatedTags = Array.from(relatedTagCounts.entries())
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([tag]) => tag);

  const sorted = [...articles].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  const { handwritten, news, reviews } = groupArticlesForHub(sorted);
  const newest: ArticleSummary | undefined = sorted[0];
  const oldest: ArticleSummary | undefined = sorted[sorted.length - 1];

  const shortKinds: string[] = [];
  if (handwritten.length) shortKinds.push(pluralize(handwritten.length, 'hand-written piece'));
  if (news.length) shortKinds.push(pluralize(news.length, 'news issue'));
  if (reviews.length) shortKinds.push(pluralize(reviews.length, 'AI paper review'));

  const detailedKinds: string[] = [];
  if (handwritten.length) detailedKinds.push(describeHandwrittenKinds(handwritten));
  if (news.length) {
    const dailies = news.filter((a) => a.type === 'News Digest').length;
    const weeklies = news.length - dailies;
    detailedKinds.push(
      joinWithAnd([
        ...(dailies ? [pluralize(dailies, 'daily digest')] : []),
        ...(weeklies ? [pluralize(weeklies, 'weekly trend report')] : []),
      ]),
    );
  }
  if (reviews.length) detailedKinds.push(pluralize(reviews.length, 'standalone AI paper review'));

  const span = newest && oldest
    ? newest.date.slice(0, 7) === oldest.date.slice(0, 7)
      ? `in ${formatMonthYear(newest.date)}`
      : `between ${formatMonthYear(oldest.date)} and ${formatMonthYear(newest.date)}`
    : '';
  const coverage = newest
    ? `Published ${span}: ${detailedKinds.join('; ')}.`
    : `No articles are tagged ${tagName} yet.`;

  const override = tagLandingOverrides[tagName];
  const latestHandwritten: ArticleSummary | undefined = handwritten[0];
  const latestHandwrittenNote =
    latestHandwritten && latestHandwritten !== newest
      ? `; the latest hand-written piece is "${latestHandwritten.title}" (${latestHandwritten.date})`
      : '';
  const lead = override?.lead
    || (newest
      ? `This hub gathers everything tagged ${tagName}: ${joinWithAnd(shortKinds)}. The most recent is "${newest.title}" (${newest.date})${latestHandwrittenNote}.`
      : `Articles about ${tagName}.`);

  const overlap = topRelatedTags.length > 0
    ? `Here ${tagName} most often overlaps with ${joinWithAnd(topRelatedTags)}.`
    : '';
  const depth = handwritten.length > 0
    ? `The hand-written ${handwritten.length === 1 ? 'piece' : 'pieces'} — ${joinWithAnd(handwritten.slice(0, 3).map((a) => a.title))} — ${handwritten.length === 1 ? 'goes' : 'go'} deepest; the daily digests and weekly reports track new papers as they appear.`
    : 'Coverage of this topic comes from the daily digests and weekly trend reports, which summarize new papers as they appear.';
  const body = override?.body || [overlap, depth].filter(Boolean).join(' ');

  const startWith = [...handwritten.slice(0, 1), ...news.slice(0, 2)].slice(0, 2);
  const learnings = [
    topRelatedTags.length > 0
      ? `Related topics: ${joinWithAnd(topRelatedTags)}.`
      : 'Related topics: secure evaluation, validation, and operational hardening.',
    startWith.length > 0
      ? `Start with: ${joinWithAnd(startWith.map((a) => a.title))}.`
      : 'Start with the most recent write-up to understand current assumptions.',
    ...(reviews.length > 0
      ? [
          `${pluralize(reviews.length, 'standalone paper review is', 'standalone paper reviews are')} listed at the end; each is also summarized in the digest of its day.`,
        ]
      : []),
  ];

  // The newest issue's compact search title ("Topics — Series, Mon D, YYYY")
  // keeps the distinguishing words inside the ~158-character snippet.
  const metaDescription = newest
    ? `${pluralize(articles.length, 'article')} on ${tagName}: ${joinWithAnd(shortKinds)}. Latest: ${getSeoTitle(newest)}.`
    : `Articles on ${tagName}.`;

  return { lead, body, coverage, learnings, relatedTags: topRelatedTags, metaDescription };
}
