import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import remarkRehype from 'remark-rehype';
import rehypeSlug from 'rehype-slug';
import rehypeHighlight from 'rehype-highlight';
import rehypeKatex from 'rehype-katex';
import rehypeStringify from 'rehype-stringify';
import { visit, SKIP } from 'unist-util-visit';
import sharp from 'sharp';
import type { Root, Element } from 'hast';
import type { Root as MdastRoot } from 'mdast';
import {
  extractDescriptionFromContent,
  inferTagsFromContent,
  isTrivialDescription,
} from '../../scripts/lib/extract-frontmatter.mjs';
import { isAutoGeneratedArticle } from '../../scripts/lib/provenance.mjs';

export interface ArticleMetadata {
  title: string;
  date: string;
  type: string;
  description: string;
  tags: string[];
  slug: string;
}

export interface Article extends ArticleMetadata {
  content: string;
  updatedAt: string;
  wordCount: number;
  readingTime: number;
  headerImage?: string;
  paperUrl?: string;
  paperAuthors?: string;
}

// Loose comparison key: lowercase, punctuation/whitespace collapsed. Generated
// bodies repeat the frontmatter title with slight punctuation variations.
function looseTextKey(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, ' ')
    .trim();
}

// The page template renders the frontmatter title as the page H1. Generated
// bodies always restate the (sometimes reworded) title as an H1, so those are
// dropped unconditionally; hand-written articles only lose an H1 when it
// loosely matches the title — a distinct human-written headline stays.
function remarkStripDuplicateTitle(options: { title: string; auto: boolean }) {
  return (tree: MdastRoot) => {
    const index = tree.children.findIndex(
      (node) => node.type === 'heading' && node.depth === 1,
    );
    if (index === -1) return;
    if (!options.auto) {
      const heading = tree.children[index] as { children?: Array<{ type: string; value?: string }> };
      const headingText = (heading.children ?? [])
        .map((c) => ('value' in c && typeof c.value === 'string' ? c.value : ''))
        .join('');
      if (looseTextKey(headingText) !== looseTextKey(options.title)) return;
    }
    tree.children.splice(index, 1);
  };
}

// Generated articles emit display equations on a single line ($$...$$), which
// remark-math treats as inline. Rewrite them to proper multi-line display form.
function normalizeDisplayMath(markdown: string): string {
  const lines = markdown.split('\n');
  const out: string[] = [];
  let inFence = false;
  for (const line of lines) {
    if (/^\s*(```|~~~)/.test(line)) {
      inFence = !inFence;
      out.push(line);
      continue;
    }
    if (!inFence) {
      const match = line.match(/^([ \t]*)\$\$(.+)\$\$[ \t]*$/);
      if (match && match[2].trim() && !match[2].includes('$$')) {
        out.push(`${match[1]}$$`, match[2].trim(), `${match[1]}$$`);
        continue;
      }
    }
    out.push(line);
  }
  return out.join('\n');
}

// Cache intrinsic image dimensions across articles (keyed by src)
const imageDimensionsCache = new Map<string, { width: number; height: number } | null>();

async function getImageDimensions(src: string): Promise<{ width: number; height: number } | null> {
  const cached = imageDimensionsCache.get(src);
  if (cached !== undefined) {
    return cached;
  }
  let dims: { width: number; height: number } | null = null;
  try {
    const fullPath = path.join(process.cwd(), 'public', src);
    const metadata = await sharp(fullPath).metadata();
    if (metadata.width && metadata.height) {
      dims = { width: metadata.width, height: metadata.height };
    }
  } catch {
    // Never fail the build over a missing/unreadable image — just skip dimensions
    dims = null;
  }
  imageDimensionsCache.set(src, dims);
  return dims;
}

// Cache webp-sibling existence checks across articles (keyed by webp src)
const webpExistsCache = new Map<string, boolean>();

function webpSiblingExists(webpSrc: string): boolean {
  const cached = webpExistsCache.get(webpSrc);
  if (cached !== undefined) {
    return cached;
  }
  const exists = fs.existsSync(path.join(process.cwd(), 'public', webpSrc));
  webpExistsCache.set(webpSrc, exists);
  return exists;
}

function rehypeLazyImages(options: { title: string }) {
  const titleKey = looseTextKey(options.title);
  return async (tree: Root) => {
    const images: Element[] = [];
    let firstImageSeen = false;
    visit(tree, 'element', (node: Element, index: number | undefined, parent: Element | Root | undefined) => {
      if (node.tagName === 'img') {
        node.properties = node.properties || {};
        if (firstImageSeen) {
          node.properties.loading = 'lazy';
        } else {
          // Treat the first image as the hero/LCP candidate
          firstImageSeen = true;
          node.properties.loading = 'eager';
          node.properties.fetchPriority = 'high';
          // Hero images echoing the title are decorative repeats for screen readers
          const altKey = looseTextKey(String(node.properties.alt ?? ''));
          if (titleKey && altKey
            && (altKey === titleKey || altKey.includes(titleKey) || titleKey.includes(altKey))) {
            node.properties.alt = '';
          }
        }
        node.properties.decoding = 'async';
        images.push(node);

        const src = String(node.properties.src || '');
        const webpSrc = src.startsWith('/') ? src.replace(/\.(png|jpe?g)$/i, '.webp') : src;
        if (webpSrc !== src && webpSiblingExists(webpSrc) && parent && typeof index === 'number') {
          const picture: Element = {
            type: 'element',
            tagName: 'picture',
            properties: {},
            children: [
              {
                type: 'element',
                tagName: 'source',
                properties: { srcSet: webpSrc, type: 'image/webp' },
                children: [],
              },
              node,
            ],
          };
          parent.children[index] = picture;
        }
      }
    });

    // Set intrinsic width/height so the browser reserves space (prevents CLS)
    for (const node of images) {
      const src = String(node.properties?.src || '');
      if (src.startsWith('/')) {
        const dims = await getImageDimensions(src);
        if (dims && node.properties) {
          node.properties.width = dims.width;
          node.properties.height = dims.height;
        }
      }
    }
  };
}

// Wide tables clip on phones: html/body clip overflow-x and .article-content
// table is width:100% with no scroll rule, so columns past the viewport edge
// are unreachable at ~375px. Wrap each <table> in a scroll container (mirrors
// the .katex-display fix in globals.css). The wrapper is a div, not
// display:block on the table, so table semantics stay intact for screen
// readers. Returning SKIP stops descent into the table's own rows and lets the
// parent loop advance past the wrapper, so the table is never re-wrapped.
function rehypeWrapTables() {
  return (tree: Root) => {
    visit(tree, 'element', (node: Element, index: number | undefined, parent: Element | Root | undefined) => {
      if (node.tagName !== 'table' || !parent || typeof index !== 'number') return;
      parent.children[index] = {
        type: 'element',
        tagName: 'div',
        properties: { className: ['table-scroll'] },
        children: [node],
      };
      return SKIP;
    });
  };
}

const articlesDirectory = path.join(process.cwd(), 'src', 'content', 'articles');

// Simple build-time cache to avoid reprocessing articles
const articleCache = new Map<string, Article | null>();

export async function getArticleBySlug(slug: string): Promise<Article | null> {
  // Check cache first
  if (articleCache.has(slug)) {
    return articleCache.get(slug) || null;
  }
  try {
    const fullPath = path.join(articlesDirectory, `${slug}.md`);
    const fileContents = fs.readFileSync(fullPath, 'utf8');
    const { data, content } = matter(fileContents);
    const wordCount = content.split(/\s+/).filter(Boolean).length;
    // CI checkouts reset file mtimes, so derive the updated date from frontmatter
    const updatedAt = String(data.updated || data.date || '');

    // Process markdown to HTML
    const processedContent = await unified()
      .use(remarkParse)
      .use(remarkStripDuplicateTitle, {
        title: String(data.title || ''),
        auto: isAutoGeneratedArticle({ type: data.type, title: data.title, date: data.date }),
      })
      .use(remarkGfm)
      .use(remarkMath)
      .use(remarkRehype)
      .use(rehypeSlug)
      .use(rehypeKatex)
      .use(rehypeHighlight)
      .use(rehypeWrapTables)
      .use(rehypeLazyImages, { title: String(data.title || '') })
      .use(rehypeStringify)
      .process(normalizeDisplayMath(content));

    const contentHtml = processedContent.toString();

    const rawDescription: string = data.description ? String(data.description).trim() : '';
    const rawTags: string[] = Array.isArray(data.tags)
      ? (data.tags as unknown[]).filter((t): t is string => typeof t === 'string')
      : [];
    const description: string = isTrivialDescription(rawDescription, data.title || '')
      ? (extractDescriptionFromContent(content) || rawDescription)
      : rawDescription;
    const tags: string[] = rawTags.length > 0 ? rawTags : inferTagsFromContent(content);
    const readingTime = Number(data.readingTime) > 0
      ? Math.ceil(Number(data.readingTime))
      : Math.ceil(wordCount / 200);

    const article: Article = {
      slug,
      title: data.title || '',
      date: data.date || '',
      type: data.type || 'Article',
      description,
      tags,
      content: contentHtml,
      updatedAt,
      wordCount,
      readingTime,
      ...(typeof data.headerImage === 'string' && data.headerImage
        ? { headerImage: data.headerImage }
        : {}),
      ...(typeof data.paperUrl === 'string' && data.paperUrl
        ? { paperUrl: data.paperUrl }
        : {}),
      ...(typeof data.paperAuthors === 'string' && data.paperAuthors
        ? { paperAuthors: data.paperAuthors }
        : {}),
    };

    // Cache the result
    articleCache.set(slug, article);
    return article;
  } catch (error) {
    console.error(`Error loading article ${slug}:`, error);
    articleCache.set(slug, null);
    return null;
  }
}

export function getAllArticleSlugs(): string[] {
  try {
    if (!fs.existsSync(articlesDirectory)) {
      return [];
    }
    const fileNames = fs.readdirSync(articlesDirectory);
    return fileNames
      .filter(fileName => fileName.endsWith('.md'))
      .map(fileName => fileName.replace(/\.md$/, ''));
  } catch (error) {
    console.error('Error reading articles directory:', error);
    return [];
  }
}

export function calculateReadingTime(content: string): number {
  const wordsPerMinute = 200;
  const words = content.split(/\s+/).length;
  return Math.ceil(words / wordsPerMinute);
}

const NAMED_ENTITIES: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  nbsp: ' ',
  ndash: '–',
  mdash: '—',
  hellip: '…',
};

function decodeHtmlEntities(text: string): string {
  return text
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(parseInt(hex, 16)))
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(parseInt(dec, 10)))
    .replace(/&([a-zA-Z]+);/g, (match, name) => NAMED_ENTITIES[name] ?? match);
}

// Generate table of contents from HTML
export function generateTOC(htmlContent: string): Array<{ level: number; text: string; id: string }> {
  const headingRegex = /<h([2-3])([^>]*)>(.*?)<\/h\1>/g;
  const toc: Array<{ level: number; text: string; id: string }> = [];
  let match;

  while ((match = headingRegex.exec(htmlContent)) !== null) {
    const level = parseInt(match[1]);
    const attrs = match[2];
    let text = match[3];
    let prev;
    do {
      prev = text;
      text = text.replace(/<[^>]*>/g, '');
    } while (text !== prev);
    text = decodeHtmlEntities(text);
    const idMatch = attrs.match(/\sid="([^"]+)"/);
    const id = idMatch?.[1] || text
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/(^-|-$)/g, '');
    toc.push({ level, text, id });
  }

  return toc;
}
