import type { Metadata } from 'next';

// Every social card is a 1200x630 PNG rendered by scripts/generate-og-images.mjs
// into public/og (git-tracked; also regenerated by `npm run build`). `name` is
// the file stem: an article slug, or one of the underscore-prefixed static
// cards that script also emits (_site, _section-<hub>, _tag-<topic-slug>).
// Width/height/type are emitted as og:image:* so Slack, LinkedIn and Discord
// can lay the unfurl out before fetching the image.
export function ogCard(name: string, alt: string) {
  return {
    url: `/og/${name}.png`,
    width: 1200,
    height: 630,
    type: 'image/png',
    alt,
  } as const;
}

export const siteMetadata = {
  siteUrl: 'https://deniskim1.com',
  siteName: 'Minseok Kim Portfolio',
  authorName: 'Minseok (Denis) Kim',
  title: 'Minseok (Denis) Kim - AI & Security Researcher',
  description:
    'Research portfolio of Minseok (Denis) Kim, focusing on AI security, RAG systems, LLM safety, and adversarial machine learning.',
  // Site-wide default unfurl image: the branded site card, inherited by the
  // root layout, the homepage, and any page or article without a card of its
  // own. Never point this at a page screenshot — Slack/LinkedIn render it as
  // the preview for every URL that lacks a specific card.
  ogImage: ogCard('_site', 'Minseok (Denis) Kim — AI & Security Researcher, deniskim1.com'),
  profiles: [
    'https://github.com/DenisKimskku',
    'https://scholar.google.com/citations?user=81uf6x0AAAAJ',
  ],
} as const;

// Next.js metadata merges `openGraph` shallowly too: any page that defines its
// own openGraph drops the layout's og:site_name and og:locale. Every page that
// sets openGraph must build it through this helper so both always survive.
//
// Twitter/X cards are deliberately NOT configured anywhere: Next.js derives
// twitter:card/title/description/image from each page's resolved openGraph
// when no `twitter` field exists (summary_large_image whenever og:image is
// set). A `twitter` block in the root layout would be inherited verbatim by
// every page that only sets openGraph, pinning twitter:image to the site card
// on article pages — so keep relying on the derivation.
export function buildOpenGraph(overrides: NonNullable<Metadata['openGraph']>) {
  return {
    siteName: siteMetadata.siteName,
    locale: 'en_US',
    ...overrides,
  };
}

// Next.js metadata merges `alternates` shallowly, so a page that sets only
// `canonical` would drop the layout's RSS autodiscovery link. Every page that
// sets alternates must build them through this helper to keep the RSS type.
export function buildAlternates(canonical?: string, feedPath: string = '/rss.xml') {
  return {
    ...(canonical ? { canonical } : {}),
    types: {
      // Sitewide default is the everything feed; section hubs (e.g. /news/)
      // may advertise their own feed instead.
      'application/rss+xml': `${siteMetadata.siteUrl}${feedPath}`,
    },
  };
}
