import { test } from 'node:test';
import assert from 'node:assert/strict';
import {
  AUTOMATION_START,
  AUTOMATION_TYPES,
  isAutoGeneratedArticle,
} from '../scripts/lib/provenance.mjs';

test('AUTOMATION_START is the documented cutover date', () => {
  assert.equal(AUTOMATION_START, '2026-03-01');
});

test('automation types dated on/after AUTOMATION_START are auto-generated', () => {
  for (const type of AUTOMATION_TYPES) {
    assert.equal(
      isAutoGeneratedArticle({ type, title: 'Some Article', date: '2026-06-15' }),
      true,
      `${type} after cutover should be auto`
    );
  }
});

test('boundary date exactly 2026-03-01 counts as auto-generated (>= semantics)', () => {
  assert.equal(
    isAutoGeneratedArticle({ type: 'Paper Review', title: 'X', date: '2026-03-01' }),
    true
  );
});

test('automation types dated before AUTOMATION_START are hand-written', () => {
  assert.equal(
    isAutoGeneratedArticle({ type: 'Paper Review', title: 'X', date: '2026-02-28' }),
    false
  );
  assert.equal(
    isAutoGeneratedArticle({ type: 'News Digest', title: 'X', date: '2025-12-31' }),
    false
  );
});

test('"This Week in AI Security" title prefix is always auto, regardless of type/date', () => {
  assert.equal(
    isAutoGeneratedArticle({
      type: 'Paper Walkthrough',
      title: 'This Week in AI Security — Feb 2026',
      date: '2026-02-01',
    }),
    true
  );
  // Prefix rule, not substring: a title merely mentioning it is not auto.
  assert.equal(
    isAutoGeneratedArticle({
      type: 'Paper Walkthrough',
      title: 'About This Week in AI Security',
      date: '2026-02-01',
    }),
    false
  );
});

test('hand-written types are never auto-generated, even after the cutover', () => {
  for (const type of ['Paper Walkthrough', 'Research Paper', 'Tutorial', 'Project']) {
    assert.equal(
      isAutoGeneratedArticle({ type, title: 'Deep Dive', date: '2026-06-15' }),
      false,
      `${type} must never be auto`
    );
  }
});

test('missing fields never crash and default to not-auto', () => {
  assert.equal(isAutoGeneratedArticle({}), false);
  assert.equal(isAutoGeneratedArticle({ type: 'Paper Review' }), false);
  assert.equal(isAutoGeneratedArticle({ type: null, title: null, date: null }), false);
});
