import { CATEGORY_CONFIG, getArticleTypeDisplay, getCategory } from '@/lib/articleTypes';

// Type label for article cards and meta lines. Auto-generated pieces (per the
// shared provenance rule) render muted with a compact "auto" badge; Denis's own
// writing gets its category accent color so it stands out from the digest flood.
//
// Tailwind's content globs do not scan src/lib, so the CATEGORY_CONFIG accent
// classes are re-listed here for the scanner:
// text-blue-500 text-teal-500 text-emerald-500 text-amber-500 text-rose-500 text-cyan-500

interface ArticleTypeLabelProps {
  type: string;
  title: string;
  date: string;
}

export default function ArticleTypeLabel({ type, title, date }: ArticleTypeLabelProps) {
  const { label, auto } = getArticleTypeDisplay({ type, title, date });
  const accent = CATEGORY_CONFIG[getCategory(type)]?.color ?? 'text-[var(--color-text-muted)]';

  return (
    <span className="inline-flex items-center gap-1.5 text-xs">
      <span className={auto ? 'text-[var(--color-text-muted)]' : `font-medium ${accent}`}>
        {label}
      </span>
      {auto && (
        <span
          className="px-1 py-px rounded border border-[var(--color-border)] text-[10px] uppercase tracking-wider leading-none text-[var(--color-text-muted)]"
          title="Generated by the automated review pipeline"
        >
          auto
        </span>
      )}
    </span>
  );
}
