// The external daily automation began bulk-publishing in March 2026. Articles
// of the automated types dated before then are hand-written (e.g. the
// 2024-2025 Paper Reviews), so provenance cannot be inferred from type alone.
// Shared by the article page (AI disclosure), the markdown pipeline (H1
// stripping), and the content linter (authorship/fabrication rules) so all
// three agree on which articles are machine-generated.
export const AUTOMATION_TYPES = new Set(['Paper Review', 'News Digest', 'Trend Report']);
export const AUTOMATION_START = '2026-03-01';

// Every frontmatter `type` the site knows how to render: the raw values used
// across the corpus plus 'Article', the loader's fallback when frontmatter
// omits `type` (src/lib/markdown.ts). Keep in sync with the display taxonomy
// in src/lib/articleTypes.ts (CATEGORY_CONFIG groups these for readers) and
// the per-type accents in scripts/generate-og-images.mjs. The content linter
// warns on anything outside this set so a typo from the automation ("Paper
// review", "Digest") surfaces before it silently falls through display code.
export const KNOWN_ARTICLE_TYPES = new Set([
  'News Digest',
  'Trend Report',
  'Paper Review',
  'Paper Walkthrough',
  'Research Paper',
  'Tutorial',
  'Project',
  'Article',
]);

export function isAutoGeneratedArticle({ type, title, date }) {
  if (String(title ?? '').startsWith('This Week in AI Security')) return true;
  return AUTOMATION_TYPES.has(String(type ?? '')) && String(date ?? '') >= AUTOMATION_START;
}
