// The external daily automation began bulk-publishing in March 2026. Articles
// of the automated types dated before then are hand-written (e.g. the
// 2024-2025 Paper Reviews), so provenance cannot be inferred from type alone.
// Shared by the article page (AI disclosure), the markdown pipeline (H1
// stripping), and the content linter (authorship/fabrication rules) so all
// three agree on which articles are machine-generated.
export const AUTOMATION_TYPES = new Set(['Paper Review', 'News Digest', 'Trend Report']);
export const AUTOMATION_START = '2026-03-01';

export function isAutoGeneratedArticle({ type, title, date }) {
  if (String(title ?? '').startsWith('This Week in AI Security')) return true;
  return AUTOMATION_TYPES.has(String(type ?? '')) && String(date ?? '') >= AUTOMATION_START;
}
