#!/usr/bin/env node
// Credit-free content linter: blocks the build on machine-certain fabrications.
// (1) placeholder/fake CVE IDs, (2) dead internal /writing/<slug> links,
// (3) first-person authorship claims in auto-generated digests, (4) HTML in
// frontmatter title/description, (5) overweight local images, (6) fabricated
// corpus stats in digests. Deterministic, no network.
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { repairFrontmatterEscapes } from './lib/frontmatter-escapes.mjs';
import { isAutoGeneratedArticle } from './lib/provenance.mjs';

const ARTDIR = path.join(process.cwd(), 'src', 'content', 'articles');
const PUBDIR = path.join(process.cwd(), 'public');
const files = fs.readdirSync(ARTDIR).filter((f) => f.endsWith('.md'));
const validSlugs = new Set(files.map((f) => f.replace(/\.md$/, '')));

const PLACEHOLDER = new Set(['1234', '12345', '123456', '0000', '00000', '0001', '1111', '11111', '9999']);
const CVE = /CVE-\d{4}-(\d{4,7})/gi;
const LINK = /\/writing\/([a-z0-9_-]+)/gi;
const MD_IMAGE = /!\[[^\]]*\]\((\/images\/[^)\s]+)/g;
const MAX_IMAGE_BYTES = 300 * 1024;

// The daily automation writes in the site owner's voice; it must never claim
// his authorship of external work. Provenance (scripts/lib/provenance.mjs)
// separates machine-generated articles from hand-written ones, which
// legitimately use first person about his own papers.
const AUTHORSHIP = [/\bmy work on\b/i, /\bI (?:previously )?proposed\b/i, /\bmy paper\b/i, /\bwe propose\b/i];
const FAKE_STATS = [/knowledge base of [0-9,]+ papers/i, /averaging [0-9.]+ citations/i];

const problems = [];
for (const f of files) {
  const text = fs.readFileSync(path.join(ARTDIR, f), 'utf8');
  let yamlError = null;
  let fm = null;
  try {
    fm = matter(text);
  } catch (err) {
    // Broken frontmatter would otherwise be silently dropped by the article
    // loader (src/lib/markdown.ts catches parse errors and returns null).
    yamlError = String(err.message).split('\n')[0];
  }
  // Even when YAML parses, raw backslashes in quoted values (LaTeX like
  // $\theta$) silently mangle the text via valid escape sequences.
  const badEscapes = !yamlError && repairFrontmatterEscapes(text) !== null;
  const ph = new Set();
  for (const m of text.matchAll(CVE)) if (PLACEHOLDER.has(m[1])) ph.add(m[0]);
  const dead = new Set();
  for (const m of text.matchAll(LINK)) {
    const tgt = m[1];
    if (tgt === 'archive' || tgt === 'tag') continue;
    if (!validSlugs.has(tgt)) dead.add(tgt);
  }

  const data = fm ? fm.data : {};
  const title = String(data.title ?? '');
  const description = String(data.description ?? '');
  const isAutoGenerated = isAutoGeneratedArticle({ type: data.type, title, date: data.date });

  const authorship = [];
  const fakeStats = [];
  if (isAutoGenerated) {
    for (const re of AUTHORSHIP) {
      const m = text.match(re);
      if (m) authorship.push(m[0]);
    }
    for (const re of FAKE_STATS) {
      const m = text.match(re);
      if (m) fakeStats.push(m[0]);
    }
  }

  const htmlFields = [];
  if (fm) {
    if (title.includes('<')) htmlFields.push('title');
    if (description.includes('<')) htmlFields.push('description');
  }

  const heavyImages = [];
  const imageRefs = new Set();
  if (typeof data.headerImage === 'string' && data.headerImage.startsWith('/images/')) imageRefs.add(data.headerImage);
  for (const m of text.matchAll(MD_IMAGE)) imageRefs.add(m[1]);
  for (const ref of imageRefs) {
    let abs;
    try {
      abs = path.join(PUBDIR, decodeURIComponent(ref));
    } catch {
      continue;
    }
    // Missing files are a different problem (broken image), not this rule's.
    if (!fs.existsSync(abs)) continue;
    const bytes = fs.statSync(abs).size;
    if (bytes <= MAX_IMAGE_BYTES) continue;
    // A heavy original passes when a light .webp sibling exists — <picture>
    // serves the sibling to effectively every browser. optimize-images.mjs
    // runs before this lint in the build chain, so CI always has siblings.
    const webp = abs.replace(/\.(png|jpe?g)$/i, '.webp');
    if (webp !== abs && fs.existsSync(webp) && fs.statSync(webp).size <= MAX_IMAGE_BYTES) continue;
    heavyImages.push(`${ref} (${Math.round(bytes / 1024)}KB)`);
  }

  if (ph.size || dead.size || yamlError || badEscapes || authorship.length || fakeStats.length || htmlFields.length || heavyImages.length) {
    problems.push({ slug: f.replace(/\.md$/, ''), ph: [...ph], dead: [...dead], yamlError, badEscapes, authorship, fakeStats, htmlFields, heavyImages });
  }
}

if (problems.length) {
  console.error('✗ Content lint FAILED:\n');
  for (const p of problems) {
    if (p.ph.length) console.error(`  ${p.slug}: placeholder CVE(s) ${p.ph.join(', ')}`);
    if (p.dead.length) console.error(`  ${p.slug}: dead internal link(s) ${p.dead.map((d) => '/writing/' + d).join(', ')}`);
    if (p.yamlError) console.error(`  ${p.slug}: unparseable frontmatter — ${p.yamlError} (\`npm run generate:index\` may auto-repair)`);
    if (p.badEscapes) console.error(`  ${p.slug}: raw backslash escapes in quoted frontmatter values would ship mangled (run \`npm run generate:index\` to auto-repair)`);
    if (p.authorship.length) console.error(`  ${p.slug}: auto-generated article claims first-person authorship of external work: ${p.authorship.map((a) => `"${a}"`).join(', ')}`);
    if (p.fakeStats.length) console.error(`  ${p.slug}: fabricated corpus statistics: ${p.fakeStats.map((s) => `"${s}"`).join(', ')}`);
    if (p.htmlFields.length) console.error(`  ${p.slug}: '<' in frontmatter ${p.htmlFields.join(' and ')} (HTML injection risk in meta tags)`);
    if (p.heavyImages.length) console.error(`  ${p.slug}: image(s) over ${MAX_IMAGE_BYTES / 1024}KB: ${p.heavyImages.join(', ')} (run \`node scripts/optimize-images.mjs\`)`);
  }
  console.error('\nRemove these before building. (scripts/lint-content.mjs)');
  process.exit(1);
}
console.log(`✓ Content lint passed (${files.length} articles; valid frontmatter, no placeholder CVEs, dead internal links, authorship claims, fabricated stats, HTML in metadata, or overweight images).`);
