#!/usr/bin/env node
// Credit-free content linter: blocks the build on machine-certain fabrications.
// (1) placeholder/fake CVE IDs, (2) dead internal /writing/<slug> links,
// (3) first-person authorship claims in auto-generated digests, (4) HTML in
// frontmatter title/description, (5) overweight local images, (6) fabricated
// corpus stats in digests, (7) frontmatter schema (title/date/type/description/
// slug uniqueness) — warn-only unless --strict. Deterministic, no network.
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import { repairFrontmatterEscapes } from './lib/frontmatter-escapes.mjs';
import { isAutoGeneratedArticle, KNOWN_ARTICLE_TYPES } from './lib/provenance.mjs';

// Frontmatter *schema* violations (bad date, unknown type, long description,
// duplicate slug) are a softer tier than the fabrication rules above: the
// daily automation pushes straight to main, so in the deploy path they warn
// without failing the build (content must never block a deploy). --strict
// (dev / PR use, same convention as generate-index.mjs) promotes them to
// failures.
const STRICT = process.argv.includes('--strict');

const ARTDIR = path.join(process.cwd(), 'src', 'content', 'articles');
const PUBDIR = path.join(process.cwd(), 'public');
const files = fs.readdirSync(ARTDIR).filter((f) => f.endsWith('.md'));
const validSlugs = new Set(files.map((f) => f.replace(/\.md$/, '')));

const DATE_FMT = /^\d{4}-\d{2}-\d{2}$/;
const MAX_DESCRIPTION_CHARS = 400;

// The slug IS the filename; the export serves it case-sensitively, so two
// files differing only by case (fine on this Windows checkout, distinct
// routes on the Linux CI runner) are near-certain duplicates of one article.
const slugCasings = new Map();
for (const f of files) {
  const slug = f.replace(/\.md$/, '');
  const key = slug.toLowerCase();
  if (!slugCasings.has(key)) slugCasings.set(key, []);
  slugCasings.get(key).push(slug);
}
const duplicateSlugs = [...slugCasings.values()].filter((v) => v.length > 1);

const PLACEHOLDER = new Set(['1234', '12345', '123456', '0000', '00000', '0001', '1111', '11111', '9999']);
const CVE = /CVE-\d{4}-(\d{4,7})/gi;
const LINK = /\/writing\/([a-z0-9_-]+)/gi;
const MD_IMAGE = /!\[[^\]]*\]\((\/images\/[^)\s]+)/g;
const MAX_IMAGE_BYTES = 300 * 1024;

// The daily automation writes in the site owner's voice; it must never claim
// his authorship of external work. Provenance (scripts/lib/provenance.mjs)
// separates machine-generated articles from hand-written ones, which
// legitimately use first person about his own papers.
const AUTHORSHIP = [/\bmy work on\b/i, /\bI (?:previously )?proposed\b/i, /\bmy paper\b/i, /\bwe propose\b/i];
const FAKE_STATS = [/knowledge base of [0-9,]+ papers/i, /averaging [0-9.]+ citations/i];

const problems = [];
const schemaWarnings = []; // { slug, issues: string[] } — warn-only unless --strict
for (const f of files) {
  const text = fs.readFileSync(path.join(ARTDIR, f), 'utf8');
  let yamlError = null;
  let fm = null;
  try {
    fm = matter(text);
  } catch (err) {
    // Broken frontmatter would otherwise be silently dropped by the article
    // loader (src/lib/markdown.ts catches parse errors and returns null).
    yamlError = String(err.message).split('\n')[0];
  }
  // Even when YAML parses, raw backslashes in quoted values (LaTeX like
  // $\theta$) silently mangle the text via valid escape sequences.
  const badEscapes = !yamlError && repairFrontmatterEscapes(text) !== null;
  const ph = new Set();
  for (const m of text.matchAll(CVE)) if (PLACEHOLDER.has(m[1])) ph.add(m[0]);
  const dead = new Set();
  for (const m of text.matchAll(LINK)) {
    const tgt = m[1];
    if (tgt === 'archive' || tgt === 'tag') continue;
    if (!validSlugs.has(tgt)) dead.add(tgt);
  }

  const data = fm ? fm.data : {};
  const title = String(data.title ?? '');
  const description = String(data.description ?? '');
  const isAutoGenerated = isAutoGeneratedArticle({ type: data.type, title, date: data.date });

  const authorship = [];
  const fakeStats = [];
  if (isAutoGenerated) {
    for (const re of AUTHORSHIP) {
      const m = text.match(re);
      if (m) authorship.push(m[0]);
    }
    for (const re of FAKE_STATS) {
      const m = text.match(re);
      if (m) fakeStats.push(m[0]);
    }
  }

  const htmlFields = [];
  if (fm) {
    if (title.includes('<')) htmlFields.push('title');
    if (description.includes('<')) htmlFields.push('description');
  }

  // Frontmatter schema (skipped when the YAML itself is broken — that is
  // already reported above and every field read would be noise on top of it).
  const schema = [];
  if (fm && !yamlError) {
    if (typeof data.title !== 'string' || !data.title.trim()) {
      schema.push(data.title === undefined ? 'title is missing' : `title must be a non-empty string (got ${JSON.stringify(data.title)})`);
    }
    if (typeof data.date !== 'string' || !DATE_FMT.test(data.date)) {
      // Unquoted YAML dates parse to Date objects, which break the string
      // comparison in provenance.mjs — hence "quoted" in the message.
      schema.push(data.date === undefined ? 'date is missing' : `date must be a quoted YYYY-MM-DD string (got ${JSON.stringify(data.date)})`);
    } else {
      const parsed = Date.parse(`${data.date}T00:00:00Z`);
      if (Number.isNaN(parsed) || new Date(parsed).toISOString().slice(0, 10) !== data.date) {
        schema.push(`date "${data.date}" is not a real calendar date`);
      }
    }
    if (typeof data.type !== 'string' || !KNOWN_ARTICLE_TYPES.has(data.type)) {
      schema.push(data.type === undefined
        ? "type is missing (the loader would silently default it to 'Article')"
        : `unknown type ${JSON.stringify(data.type)} — known: ${[...KNOWN_ARTICLE_TYPES].join(', ')}`);
    }
    if (data.description !== undefined) {
      if (typeof data.description !== 'string') {
        schema.push(`description must be a string (got ${typeof data.description})`);
      } else if (data.description.length >= MAX_DESCRIPTION_CHARS) {
        schema.push(`description is ${data.description.length} chars (must be under ${MAX_DESCRIPTION_CHARS})`);
      }
    }
  }
  if (schema.length) schemaWarnings.push({ slug: f.replace(/\.md$/, ''), issues: schema });

  const heavyImages = [];
  const imageRefs = new Set();
  if (typeof data.headerImage === 'string' && data.headerImage.startsWith('/images/')) imageRefs.add(data.headerImage);
  for (const m of text.matchAll(MD_IMAGE)) imageRefs.add(m[1]);
  for (const ref of imageRefs) {
    let abs;
    try {
      abs = path.join(PUBDIR, decodeURIComponent(ref));
    } catch {
      continue;
    }
    // Missing files are a different problem (broken image), not this rule's.
    if (!fs.existsSync(abs)) continue;
    const bytes = fs.statSync(abs).size;
    if (bytes <= MAX_IMAGE_BYTES) continue;
    // A heavy original passes when a light .webp sibling exists — <picture>
    // serves the sibling to effectively every browser. optimize-images.mjs
    // runs before this lint in the build chain, so CI always has siblings.
    const webp = abs.replace(/\.(png|jpe?g)$/i, '.webp');
    if (webp !== abs && fs.existsSync(webp) && fs.statSync(webp).size <= MAX_IMAGE_BYTES) continue;
    heavyImages.push(`${ref} (${Math.round(bytes / 1024)}KB)`);
  }

  if (ph.size || dead.size || yamlError || badEscapes || authorship.length || fakeStats.length || htmlFields.length || heavyImages.length) {
    problems.push({ slug: f.replace(/\.md$/, ''), ph: [...ph], dead: [...dead], yamlError, badEscapes, authorship, fakeStats, htmlFields, heavyImages });
  }
}

const schemaIssueCount = schemaWarnings.reduce((n, w) => n + w.issues.length, 0) + duplicateSlugs.length;
if (schemaIssueCount) {
  // Deploy (non-strict) path: warn and keep going — a malformed field from
  // the automation must never block a site deploy. --strict fails below.
  console.error(`${STRICT ? '✗' : '⚠'} Frontmatter schema ${STRICT ? 'FAILED (--strict)' : 'warnings'}:\n`);
  for (const dup of duplicateSlugs) {
    console.error(`  duplicate slug (case-insensitive): ${dup.join(' vs ')}`);
  }
  for (const w of schemaWarnings) {
    for (const issue of w.issues) console.error(`  ${w.slug}: ${issue}`);
  }
  console.error(STRICT
    ? '\nFix the frontmatter above. (scripts/lint-content.mjs --strict)\n'
    : '\nNot blocking the build; run `node scripts/lint-content.mjs --strict` to enforce. (scripts/lint-content.mjs)\n');
}

if (problems.length) {
  console.error('✗ Content lint FAILED:\n');
  for (const p of problems) {
    if (p.ph.length) console.error(`  ${p.slug}: placeholder CVE(s) ${p.ph.join(', ')}`);
    if (p.dead.length) console.error(`  ${p.slug}: dead internal link(s) ${p.dead.map((d) => '/writing/' + d).join(', ')}`);
    if (p.yamlError) console.error(`  ${p.slug}: unparseable frontmatter — ${p.yamlError} (\`npm run generate:index\` may auto-repair)`);
    if (p.badEscapes) console.error(`  ${p.slug}: raw backslash escapes in quoted frontmatter values would ship mangled (run \`npm run generate:index\` to auto-repair)`);
    if (p.authorship.length) console.error(`  ${p.slug}: auto-generated article claims first-person authorship of external work: ${p.authorship.map((a) => `"${a}"`).join(', ')}`);
    if (p.fakeStats.length) console.error(`  ${p.slug}: fabricated corpus statistics: ${p.fakeStats.map((s) => `"${s}"`).join(', ')}`);
    if (p.htmlFields.length) console.error(`  ${p.slug}: '<' in frontmatter ${p.htmlFields.join(' and ')} (HTML injection risk in meta tags)`);
    if (p.heavyImages.length) console.error(`  ${p.slug}: image(s) over ${MAX_IMAGE_BYTES / 1024}KB: ${p.heavyImages.join(', ')} (run \`node scripts/optimize-images.mjs\`)`);
  }
  console.error('\nRemove these before building. (scripts/lint-content.mjs)');
  process.exit(1);
}
if (STRICT && schemaIssueCount) process.exit(1);
if (schemaIssueCount) {
  console.log(`⚠ Content lint passed with ${schemaIssueCount} frontmatter schema warning(s) (${files.length} articles).`);
} else {
  console.log(`✓ Content lint passed (${files.length} articles; valid frontmatter schema, no placeholder CVEs, dead internal links, authorship claims, fabricated stats, HTML in metadata, or overweight images).`);
}
